name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # O el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Versión de Node.js que usas

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --base-href=/angular-mvd-platform/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/website
